---
abstract: 'recursively copy Perl datatypes'
author:
  - 'Ray Finch <rdf@cpan.org>'
build_requires:
  Data::Dumper: 0
  Hash::Util::FieldHash: 0
  Scalar::Util: 0
  Storable: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clone
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Clone
  license: http://dev.perl.org/licenses/
version: 0.33
